# Generated by Django 5.0.2 on 2026-04-27 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course_id', 'user_id')},
        ),
    ]
